"""Shared reports API routes."""

from typing import Optional

from fastapi import APIRouter, HTTPException, Depends
from pydantic import BaseModel
import structlog

from app.api.auth import get_optional_user
from app.db import get_pg_pool, get_supabase_client
from app.config import get_settings
from app.datetime_support import format_api_datetime
import secrets

logger = structlog.get_logger()
router = APIRouter(prefix="/shared-reports", tags=["shared_reports"])


class SharedReportCreate(BaseModel):
    """Request model for creating a shared report."""

    title: Optional[str] = "Security Analysis Report"
    blocks: dict


class SharedReportResponse(BaseModel):
    """Response model for a shared report."""

    title: str
    blocks: dict
    created_at: str


@router.post("", response_model=dict)
async def create_shared_report(
    request: SharedReportCreate,
    current_user: Optional[dict] = Depends(get_optional_user),
):
    """Create a new shared report.

    The report is stored in the shared_reports table and a share_token is
    generated by the database. The token can be used to retrieve the report
    via the read-only endpoint.
    """
    settings = get_settings()

    # Local database-backed shared reports
    if settings.database_mode == "local":
        pool = await get_pg_pool()

        async with pool.acquire() as conn:
            row = await conn.fetchrow(
                """
                INSERT INTO shared_reports (user_id, title, blocks)
                VALUES ($1, $2, $3)
                RETURNING share_token
                """,
                current_user["id"] if current_user else None,
                request.title,
                request.blocks,
            )

            if not row:
                logger.error("Failed to insert shared report")
                raise HTTPException(status_code=500, detail="Failed to create shared report")

            return {"share_token": row["share_token"]}
    
    # Supabase-backed shared reports
    if settings.database_mode == "supabase":
        try:
            client = get_supabase_client()
            
            # Generate share_token (Supabase may not support PostgreSQL's encode function in default)
            # Using secrets module to generate a secure random token
            share_token = secrets.token_hex(16)
            
            result = client.table("shared_reports").insert({
                "user_id": current_user["id"] if current_user else None,
                "title": request.title,
                "blocks": request.blocks,
                "share_token": share_token,
            }).execute()
            
            if not result.data:
                logger.error("Failed to insert shared report")
                raise HTTPException(status_code=500, detail="Failed to create shared report")
            
            return {"share_token": share_token}
        except HTTPException:
            raise
        except Exception as e:
            logger.error("Failed to create shared report", error=str(e))
            raise HTTPException(status_code=500, detail="Failed to create shared report")
    
    # Unsupported mode
    raise HTTPException(status_code=500, detail="Unsupported database_mode for creating shared report")


@router.get("/by-token/{token}", response_model=SharedReportResponse)
async def get_shared_report_by_token(token: str):
    """Get a shared report by its public share token.

    This uses the SQL helper function get_shared_report_by_token to enforce
    expiry semantics in the database.
    """
    settings = get_settings()

    # Local database-backed shared reports
    if settings.database_mode == "local":
        pool = await get_pg_pool()

        async with pool.acquire() as conn:
            row = await conn.fetchrow(
                """
                SELECT title, blocks, created_at
                FROM get_shared_report_by_token($1)
                """,
                token,
            )

            if not row:
                raise HTTPException(status_code=404, detail="Report not found or has expired")

            return {
                "title": row["title"],
                "blocks": row["blocks"],
                "created_at": format_api_datetime(row["created_at"]),
            }
    
    # Supabase-backed shared reports
    if settings.database_mode == "supabase":
        try:
            client = get_supabase_client()
            
            # Use RPC function to get shared report by token
            result = client.rpc("get_shared_report_by_token", {"p_token": token}).execute()
            
            if not result.data or len(result.data) == 0:
                raise HTTPException(status_code=404, detail="Report not found or has expired")
            
            row = result.data[0]
            return {
                "title": row["title"],
                "blocks": row["blocks"],
                "created_at": format_api_datetime(row["created_at"]),
            }
        except HTTPException:
            raise
        except Exception as e:
            logger.error("Failed to get shared report by token", error=str(e))
            raise HTTPException(status_code=500, detail="Failed to get shared report")
    
    # Unsupported mode
    raise HTTPException(status_code=500, detail="Unsupported database_mode for getting shared report")

